site_name: QuestMath Tutoring Hub
site_url: https://math.frontecho.cn/
repo_name: frontecho/questmathdocs
repo_url: https://github.com/frontecho/questmathdocs/
edit_uri: tree/main/docs
site_description: 求索数学辅学站
copyright: Copyright &copy; 2023 <a href="https://github.com/frontecho/questmathdocs/" target="_blank" rel="noopener">QuestMath</a>

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - tables
  # - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

exclude_docs: |
  todo.md
  content.txt
  CreateFileFromContent.py

not_in_nav: |
  todo.md


nav:
  - Home:
    - index.md
  - Calculus:
    - calculus/index.md
    - 1 Functions: 
      - calculus/ch1/index.md
      - 1.1 Functions and Their Graphs: calculus/ch1/1.1.md
      - 1.2 Combining Functions; Shifting and Scaling Graphs: calculus/ch1/1.2.md
      - 1.3 Trigonometric Functions: calculus/ch1/1.3.md
      - 1.4 Graphing with Software: calculus/ch1/1.4.md
      - 1.5 Exponential Functions: calculus/ch1/1.5.md
      - 1.6 Inverse Functions and Logarithms: calculus/ch1/1.6.md
    - 2 Limits and Continuity:
      - calculus/ch2/index.md
      - 2.1 Rates of Change and Tangents to Curves: calculus/ch2/2.1.md
      - 2.2 Limit of a Function and Limit Laws: calculus/ch2/2.2.md
      - 2.3 The Precise Definition of a Limit: calculus/ch2/2.3.md
      - 2.4 One-Sided Limits: calculus/ch2/2.4.md
      - 2.5 Continuity: calculus/ch2/2.5.md
      - 2.6 Limits Involving Infinity; Asymptotes of Graphs: calculus/ch2/2.6.md
    - 3 Derivatives:
      - calculus/ch3/index.md
      - 3.1 Tangents and the Derivative at a Point: calculus/ch3/3.1.md
      - 3.2 The Derivative as a Function: calculus/ch3/3.2.md
      - 3.3 Differentiation Rules: calculus/ch3/3.3.md
      - 3.4 The Derivative as a Rate of Change: calculus/ch3/3.4.md
      - 3.5 Derivatives of Trigonometric Functions: calculus/ch3/3.5.md
      - 3.6 The Chain Rule: calculus/ch3/3.6.md
      - 3.7 Implicit Differentiation: calculus/ch3/3.7.md
      - 3.8 Derivatives of Inverse Functions and Logarithms: calculus/ch3/3.8.md
      - 3.9 Inverse Trigonometric Functions: calculus/ch3/3.9.md
      - 3.10 Related Rates: calculus/ch3/3.10.md
      - 3.11 Linearization and Differentials: calculus/ch3/3.11.md
    - 4 Applications of Derivatives:
      - calculus/ch4/index.md
      - 4.1 Extreme Values of Functions: calculus/ch4/4.1.md
      - 4.2 The Mean Value Theorem: calculus/ch4/4.2.md
      - 4.3 Monotonic Functions and the First Derivative Test: calculus/ch4/4.3.md
      - 4.4 Concavity and Curve Sketching: calculus/ch4/4.4.md
      - 4.5 Indeterminate Forms and L'Hôpital's Rule: calculus/ch4/4.5.md
      - 4.6 Applied Optimization: calculus/ch4/4.6.md
      - 4.7 Newton's Method: calculus/ch4/4.7.md
      - 4.8 Antiderivatives: calculus/ch4/4.8.md
    - 5 Integrals:
      - calculus/ch5/index.md
      - 5.1 Area and Estimating with Finite Sums: calculus/ch5/5.1.md
      - 5.2 Sigma Notation and Limits of Finite Sums: calculus/ch5/5.2.md
      - 5.3 The Definite Integral: calculus/ch5/5.3.md
      - 5.4 The Fundamental Theorem of Calculus: calculus/ch5/5.4.md
      - 5.5 Indefinite Integrals and the Substitution Method: calculus/ch5/5.5.md
      - 5.6 Definite Integral Substitutions and the Area Between Curves: calculus/ch5/5.6.md
    - 6 Applications of Definite Integrals:
      - calculus/ch6/index.md
      - 6.1 Volumes Using Cross-Sections: calculus/ch6/6.1.md
      - 6.2 Volumes Using Cylindrical Shells: calculus/ch6/6.2.md
      - 6.3 Arc Length: calculus/ch6/6.3.md
      - 6.4 Areas of Surfaces of Revolution: calculus/ch6/6.4.md
      - 6.5 Work and Fluid Forces: calculus/ch6/6.5.md
      - 6.6 Moments and Centers of Mass: calculus/ch6/6.6.md
    - 7 Integrals and Transcendental Functions:
      - calculus/ch7/index.md
      - 7.1 The Logarithm Defined as an Integral: calculus/ch7/7.1.md
      - 7.2 Exponential Change and Separable Differential Equations: calculus/ch7/7.2.md
      - 7.3 Hyperbolic Functions: calculus/ch7/7.3.md
      - 7.4 Relative Rates of Growth: calculus/ch7/7.4.md
    - 8 Techniques of Integration:
      - calculus/ch8/index.md
      - 8.1 Using Basic Integration Formulas: calculus/ch8/8.1.md
      - 8.2 Integration by Parts: calculus/ch8/8.2.md
      - 8.3 Trigonometric Integrals: calculus/ch8/8.3.md
      - 8.4 Trigonometric Substitutions: calculus/ch8/8.4.md
      - 8.5 Integration of Rational Functions by Partial Fractions: calculus/ch8/8.5.md
      - 8.6 Integral Tables and Computer Algebra Systems: calculus/ch8/8.6.md
      - 8.7 Numerical Integration: calculus/ch8/8.7.md
      - 8.8 Improper Integrals: calculus/ch8/8.8.md
      - 8.9 Probability: calculus/ch8/8.9.md
    - 9 First-Order Differential Equations:
      - calculus/ch9/index.md
      - 9.1 Solutions, Slope Fields, and Euler's Method: calculus/ch9/9.1.md
      - 9.2 First-Order Linear Equations: calculus/ch9/9.2.md
      - 9.3 Applications: calculus/ch9/9.3.md
      - 9.4 Graphical Solutions of Autonomous Equations: calculus/ch9/9.4.md
      - 9.5 Systems of Equations and Phase Planes: calculus/ch9/9.5.md
    - 10 Infinite Sequences and Series:
      - calculus/ch10/index.md
      - 10.1 Sequences: calculus/ch10/10.1.md
      - 10.2 Infinite Series: calculus/ch10/10.2.md
      - 10.3 The Integral Test: calculus/ch10/10.3.md
      - 10.4 Comparison Tests: calculus/ch10/10.4.md
      - 10.5 Absolute Convergence; The Ratio and Root Tests: calculus/ch10/10.5.md
      - 10.6 Alternating Series and Conditional Convergence: calculus/ch10/10.6.md
      - 10.7 Power Series: calculus/ch10/10.7.md
      - 10.8 Taylor and Maclaurin Series: calculus/ch10/10.8.md
      - 10.9 Convergence of Taylor Series: calculus/ch10/10.9.md
      - 10.10 The Binomial Series and Applications of Taylor Series: calculus/ch10/10.10.md
    - 11 Parametric Equations and Polar Coordinates:
      - calculus/ch11/index.md
      - 11.1 Parametrizations of Plane Curves: calculus/ch11/11.1.md
      - 11.2 Calculus with Parametric Curves: calculus/ch11/11.2.md
      - 11.3 Polar Coordinates: calculus/ch11/11.3.md
      - 11.4 Graphing Polar Coordinate Equations: calculus/ch11/11.4.md
      - 11.5 Areas and Lengths in Polar Coordinates: calculus/ch11/11.5.md
      - 11.6 Conic Sections: calculus/ch11/11.6.md
      - 11.7 Conics in Polar Coordinates: calculus/ch11/11.7.md
    - 12 Vectors and the Geometry of Space:
      - calculus/ch12/index.md
      - 12.1 Three-Dimensional Coordinate Systems: calculus/ch12/12.1.md
      - 12.2 Vectors: calculus/ch12/12.2.md
      - 12.3 The Dot Product: calculus/ch12/12.3.md
      - 12.4 The Cross Product: calculus/ch12/12.4.md
      - 12.5 Lines and Planes in Space: calculus/ch12/12.5.md
      - 12.6 Cylinders and Quadric Surfaces: calculus/ch12/12.6.md
    - 13 Vector-Valued Functions and Motion in Space:
      - calculus/ch13/index.md
      - 13.1 Curves in Space and Their Tangents: calculus/ch13/13.1.md
      - 13.2 Integrals of Vector Functions; Projectile Motion: calculus/ch13/13.2.md
      - 13.3 Arc Length in Space: calculus/ch13/13.3.md
      - 13.4 Curvature and Normal Vectors of a Curve: calculus/ch13/13.4.md
      - 13.5 Tangential and Normal Components of Acceleration: calculus/ch13/13.5.md
      - 13.6 Velocity and Acceleration in Polar Coordinates: calculus/ch13/13.6.md
    - 14 Partial Derivatives:
      - calculus/ch14/index.md
      - 14.1 Functions of Several Variables: calculus/ch14/14.1.md
      - 14.2 Limits and Continuity in Higher Dimensions: calculus/ch14/14.2.md
      - 14.3 Partial Derivatives: calculus/ch14/14.3.md
      - 14.4 The Chain Rule: calculus/ch14/14.4.md
      - 14.5 Directional Derivatives and Gradient Vectors: calculus/ch14/14.5.md
      - 14.6 Tangent Planes and Differentials: calculus/ch14/14.6.md
      - 14.7 Extreme Values and Saddle Points: calculus/ch14/14.7.md
      - 14.8 Lagrange Multipliers: calculus/ch14/14.8.md
      - 14.9 Taylor's Formula for Two Variables: calculus/ch14/14.9.md
      - 14.10 Partial Derivatives with Constrained Variables: calculus/ch14/14.10.md
    - 15 Multiple Integrals:
      - calculus/ch15/index.md
      - 15.1 Double and Iterated Integrals over Rectangles: calculus/ch15/15.1.md
      - 15.2 Double Integrals over General Regions: calculus/ch15/15.2.md
      - 15.3 Area by Double Integration: calculus/ch15/15.3.md
      - 15.4 Double Integrals in Polar Form: calculus/ch15/15.4.md
      - 15.5 Triple Integrals in Rectangular Coordinates: calculus/ch15/15.5.md
      - 15.6 Moments and Centers of Mass: calculus/ch15/15.6.md
      - 15.7 Triple Integrals in Cylindrical and Spherical Coordinates: calculus/ch15/15.7.md
      - 15.8 Substitutions in Multiple Integrals: calculus/ch15/15.8.md
    - 16 Integrals and Vector Fields:
      - calculus/ch16/index.md
      - 16.1 Line Integrals: calculus/ch16/16.1.md
      - 16.2 Vector Fields and Line Integrals - Work, Circulation, and Flux: calculus/ch16/16.2.md
      - 16.3 Path Independence, Conservative Fields, and Potential Functions: calculus/ch16/16.3.md
      - 16.4 Green's Theorem in the Plane: calculus/ch16/16.4.md
      - 16.5 Surfaces and Area: calculus/ch16/16.5.md
      - 16.6 Surface Integrals: calculus/ch16/16.6.md
      - 16.7 Stokes' Theorem: calculus/ch16/16.7.md
      - 16.8 The Divergence Theorem and a Unified Theory: calculus/ch16/16.8.md
    - 17 Second-Order Differential Equations online:
      - calculus/ch17/index.md
      - 17.1 Second-Order Linear Equations: calculus/ch17/17.1.md
      - 17.2 Nonhomogeneous Linear Equations: calculus/ch17/17.2.md
      - 17.3 Applications: calculus/ch17/17.3.md
      - 17.4 Euler Equations: calculus/ch17/17.4.md
      - 17.5 Power Series Solutions: calculus/ch17/17.5.md
